term.clear()
term.setCursorPos(1,1)
print("Would you like to install an app or an os?")
print("")
term.setBackgroundColor(colors.green)
print("       ")
print("  App  ")
print("       ")
term.setCursorPos(9, 3)
term.setBackgroundColor(colors.blue)
print("      ")
term.setCursorPos(9, 4)
print("  OS  ")
term.setCursorPos(9, 5)
print("      ")
