term.clear()
term.setCursorPos()
term.setBackgroundColor(colors.green)
print("            ")
print("   Change   ")
print("  Password  ")
print("            ")
term.setCursorPos(14, 1)
term.setBackgroundColor(colors.blue)
print("        ")
print("  Lock  ")
print("        ")
